services:
  database:
    image: "postgres:16.1-alpine3.19"
    env_file:
      - .env
    ports:
      - "5432:5432"

  test_database:
    image: "postgres:16.1-alpine3.19"
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"